plugins {
    // see https://fabricmc.net/develop/ for new versions
    id 'fabric-loom' version '1.7-SNAPSHOT' apply false
    // see https://projects.neoforged.net/neoforged/moddevgradle for new versions
    id 'net.neoforged.moddev' version '0.1.110' apply false
    id 'net.darkhax.curseforgegradle' version '1.1.26'
    id 'com.modrinth.minotaur' version '2.+'
}

tasks.register('latestChangelog') {
    group = "changelog"

    String fullChangelogText = file("CHANGELOG.md").getText()

    int firstHeading = fullChangelogText.indexOf("## [")
    int nextHeading = fullChangelogText.indexOf("## [", firstHeading + 1)

    String latestChangelogText = fullChangelogText.substring(firstHeading, nextHeading)

    outputs.upToDateWhen {
        if (file("LATEST_CHANGELOG.md").exists()) {
            return latestChangelogText == file("LATEST_CHANGELOG.md").getText()
        } else return false
    }

    outputs.file file("LATEST_CHANGELOG.md")
    doLast {
        def latestChangelog = file("LATEST_CHANGELOG.md")
        latestChangelog.text = latestChangelogText
        printf(latestChangelog.text)
    }
}

tasks.register('publishAll') {
    group = "upload"

    dependsOn("latestChangelog")
    dependsOn("fabric:publishFabric")
    dependsOn("forge:publishForge")
    dependsOn("neoforge:publishNeoForge")
}